const express = require('express');
const router = express.Router();
const { countryBodyValidator } = require('../middlewares/validator');
const {exportCountries} = require("../controllers/foreingExportCountriesController");
const {importCountries} = require("../controllers/foreingImportCountriesController");
const {indiaCountry} = require("../controllers/indiaCountryController");
const {weeklyApis} = require('../controllers/weekly');



// //export APIs
router.post('/getWeeklyExports', countryBodyValidator, weeklyApis.getExportWeeklyData);
router.post('/getIndiaExports', countryBodyValidator, indiaCountry.export);
router.post('/getArgentinaExports', countryBodyValidator, exportCountries.argentina);
router.post('/getBoliviaExports', countryBodyValidator, exportCountries.bolivia);
router.post('/getBotswanaExports', countryBodyValidator, exportCountries.botswana);
router.post('/getGhanaExports', countryBodyValidator, exportCountries.ghana);
router.post('/getBangladeshExports', countryBodyValidator, exportCountries.bangladesh);
router.post('/getIndonesiaExports', countryBodyValidator, exportCountries.indonesia);
router.post('/getVietnamExports', countryBodyValidator, exportCountries.vietnam);
router.post('/getNicaraguaExports', countryBodyValidator, exportCountries.nicaragua);
router.post('/getPanamaExports', countryBodyValidator, exportCountries.panama);
router.post('/getTanzaniaExports', countryBodyValidator, exportCountries.tanzania);
router.post('/getSrilankaExports', countryBodyValidator, exportCountries.srilanka);
router.post('/getEthiopiaExports', countryBodyValidator, exportCountries.ethiopia);
router.post('/getChileExports', countryBodyValidator, exportCountries.chile);
router.post('/getPhilipExports', countryBodyValidator, exportCountries.philip);
router.post('/getTurkeyExports', countryBodyValidator, exportCountries.turkey);
router.post('/getRussiaExports', countryBodyValidator, exportCountries.russia);
router.post('/getKenyaExports', countryBodyValidator, exportCountries.kenya);
router.post('/getLesothoExports', countryBodyValidator, exportCountries.lesotho);
router.post('/getMexicoExports', countryBodyValidator, exportCountries.mexico);
router.post('/getNigeriaExports', countryBodyValidator, exportCountries.nigeria);
router.post('/getBrazilExports', countryBodyValidator, exportCountries.brazil);
router.post('/getColumbiaExports', countryBodyValidator, exportCountries.columbia);
router.post('/getParaguayExports', countryBodyValidator, exportCountries.paraguay);
router.post('/getPeruExports', countryBodyValidator, exportCountries.peru);
router.post('/getUgandaExports', countryBodyValidator, exportCountries.uganda);
router.post('/getPakistanExports', countryBodyValidator, exportCountries.pakistan);
router.post('/getNamibiaExports', countryBodyValidator, exportCountries.namibia);
router.post('/getEcuadorExports', countryBodyValidator, exportCountries.ecuador);
router.post('/getIvorycostExports', countryBodyValidator, exportCountries.ivorycost);
router.post('/getUruguayExports', countryBodyValidator, exportCountries.uruguay);
router.post('/getUzbekistanExports', countryBodyValidator, exportCountries.uzbekistan);
router.post('/getVenezuelaExports', countryBodyValidator, exportCountries.venezuela);
router.post('/getUkraineExports', countryBodyValidator, exportCountries.ukraine);
router.post('/getCostaricaExports', countryBodyValidator, exportCountries.costarica);
router.post('/getKazakhastanExports', countryBodyValidator, exportCountries.kazakhastan);
router.post('/getCostademarfilExports', countryBodyValidator, exportCountries.costademarfil);
router.post('/getUSAExports', countryBodyValidator, exportCountries.usa);
router.post('/getCameroonExports', countryBodyValidator, exportCountries.cameroon);


//import APIs
router.post('/getWeeklyImports', countryBodyValidator, weeklyApis.getImportWeeklyData);
router.post('/getIndiaImports', countryBodyValidator, indiaCountry.import);
router.post('/getArgentinaImports', countryBodyValidator, importCountries.argentina);
router.post('/getBoliviaImports', countryBodyValidator, importCountries.bolivia);
router.post('/getBurundiImports', countryBodyValidator, importCountries.burundi);
router.post('/getBotswanaImports', countryBodyValidator, importCountries.botswana);
router.post('/getCameroonImports', countryBodyValidator, importCountries.cameroon);
router.post('/getGhanaImports', countryBodyValidator, importCountries.ghana);
router.post('/getBangladeshImports', countryBodyValidator, importCountries.bangladesh);
router.post('/getIndonesiaImports', countryBodyValidator, importCountries.indonesia);
router.post('/getVietnamImports', countryBodyValidator, importCountries.vietnam);
router.post('/getNicaraguaImports', countryBodyValidator, importCountries.nicaragua);
router.post('/getPanamaImports', countryBodyValidator, importCountries.panama);
router.post('/getTanzaniaImports', countryBodyValidator, importCountries.tanzania);
router.post('/getSrilankaImports', countryBodyValidator, importCountries.srilanka);
router.post('/getEthiopiaImports', countryBodyValidator, importCountries.ethiopia);
router.post('/getChileImports', countryBodyValidator, importCountries.chile);
router.post('/getPhilipImports', countryBodyValidator, importCountries.philip);
router.post('/getTurkeyImports', countryBodyValidator, importCountries.turkey);
router.post('/getRussiaImports', countryBodyValidator, importCountries.russia);
router.post('/getKenyaImports', countryBodyValidator, importCountries.kenya);
router.post('/getLesothoImports', countryBodyValidator, importCountries.lesotho);
router.post('/getMexicoImports', countryBodyValidator, importCountries.mexico);
router.post('/getNigeriaImports', countryBodyValidator, importCountries.nigeria);
router.post('/getUsaImports', countryBodyValidator, importCountries.usa);
router.post('/getBrazilImports', countryBodyValidator, importCountries.brazil);
router.post('/getColumbiaImports', countryBodyValidator, importCountries.columbia);
router.post('/getIvorycostImports', countryBodyValidator, importCountries.ivorycost);
router.post('/getEcuadorImports', countryBodyValidator, importCountries.ecuador);
router.post('/getNamibiaImports', countryBodyValidator, importCountries.namibia);
router.post('/getPeruImports', countryBodyValidator, importCountries.peru);
router.post('/getSouthsudanImports', countryBodyValidator, importCountries.southsudan);
router.post('/getUruguayImports', countryBodyValidator, importCountries.uruguay);
router.post('/getUzbekistanImports', countryBodyValidator, importCountries.uzbekistan);
router.post('/getVenezuelaImports', countryBodyValidator, importCountries.venezuela);
router.post('/getUkraineImports', countryBodyValidator, importCountries.ukraine);
router.post('/getCostaricaImports', countryBodyValidator, importCountries.costarica);
router.post('/getKazakhastanImports', countryBodyValidator, importCountries.kazakhastan);
router.post('/getPakistanImports', countryBodyValidator, importCountries.pakistan);
router.post('/getCostademarfilImports', countryBodyValidator, importCountries.costademarfil);
router.post('/getParaguayImports', countryBodyValidator, importCountries.paraguay);
router.post('/getRwandaImports', countryBodyValidator, importCountries.rwanda);
router.post('/getUgandaImports', countryBodyValidator, importCountries.uganda);

module.exports = router;
