module.exports = {
    export: {
        mirror: ['"RecordID"', '"TYPE"', '"Date"', '"HsCode"', '"ProductDesc_Native"', '"ProductDesc"', '"Quantity"', '"uqc"', '"UnitPriceFC"', '"Currency"', '"ValueInUSD"', '"Exp_Name_Native"', '"Exp_Name"', '"Imp_Name_Native"', '"Imp_Name"', '"CountryofDestination"'],
        china: ["*"],
        statistical: ["'RecordID'", "'HsCode'","'ProductDesc'","'Quantity'","'uqc'","'Currency'","'ValueInUSD'", "'CountryofDestination'"],
        india: ['"RecordID"', '"Type"', '"Date"', '"HsCode"', '"ProductDesc"', '"Exp_Name"', '"Imp_Name"', '"CountryofDestination"', '"uqc"', '"Mode"', '"Quantity"', '"Currency"', '"UnitPriceFC"', '"InvValueFC"', '"ValueInUSD"', '"Exchange_Rate"', '"PortofDestination"', '"PortofOrigin"', '"SB_NO"'],
        weekly: ['"RecordID"', '"Date"', '"HsCode"', '"Exp_Name"', '"Imp_Name"', '"CountryofDestination"', '"ProductDesc"', '"Quantity"', '"uqc"', '"Mode"', '"Currency"', '"FOB"', '"PortofOrigin"', '"PortofDestination"', '"Item_NO"', '"Invoice_NO"', '"UnitPriceFC"', '"Drawback"', '"port_code"'],
        argentina: ["*"],
        bolivia: ["*"],
        botswana: ["*"],
        ghana: ["*"],
        bangladesh: ["*"],
        indonesia: ["*"],
        vietnam: ["*"],
        nicaragua: ["*"],
        panama: ["*"],
        tanzania: ["*"],
        srilanka: ["*"],
        ethiopia: ["*"],
        chile: ["*"],
        philip: ["*"],
        turkey: ["*"],
        russia: ["*"],
        kenya: ["*"],
        lesotho: ["*"],
        mexico: ["*"],
        usa: ["*"],
        nigeria: ["*"],
        brazil: ["*"],
        columbia: ["*"],
        paraguay: ["*"],
        peru: ["*"],
        uganda: ["*"],
        pakistan: ["*"],
        namibia: ["*"],
        ecuador: ["*"],
        ivorycost: ["*"],
        uruguay: ["*"],
        uzbekistan: ["*"],
        venezuela: ["*"],
        ukraine: ["*"],
        cameroon: ["*"],
        costarica: ["*"],
        kazakhastan: ["*"],
        costademarfil: ["*"],
    },

    import: {
        mirror: ['"RecordID"', '"TYPE"', '"Date"', '"HsCode"', '"ProductDesc_Native"', '"ProductDesc"', '"Quantity"', '"uqc"', '"UnitPriceFC"', '"Currency"', '"ValueInUSD"', '"Exp_Name_Native"', '"Exp_Name"', '"Imp_Name_Native"', '"Imp_Name"', '"CountryofOrigin"'],
        statistical: ["'RecordID'", "'HsCode'","'ProductDesc'","'Quantity'","'uqc'","'Currency'","'ValueInUSD'", "'CountryofOrigin'"],
        china: ["*"],
        india: ['"RecordID"', '"Type"', '"Date"', '"HsCode"', '"ProductDesc"', '"Exp_Name"', '"Imp_Name"', '"CountryofOrigin"', '"uqc"', '"Mode"', '"Quantity"', '"Currency"', '"UnitPriceFC"', '"InvValueFC"', '"Duty_USD"', '"Duty_PCNTG"', '"Exchange_Rate"', '"Importer_Value_USD"', '"ValueInUSD"', '"PortofOrigin"', '"PortofDestination"', '"BE_NO"'],
        weekly: ['"RecordID"', '"Date"', '"HsCode"', '"Exp_Name"', '"Imp_Name"', '"CountryofOrigin"', '"ProductDesc"', '"Quantity"', '"uqc"', '"Currency"'],
        argentina: ["*"],
        bolivia: ["*"],
        burundi: ["*"],
        botswana: ["*"],
        cameroon: ["*"],
        ghana: ["*"],
        bangladesh: ["*"],
        indonesia: ["*"],
        vietnam: ["*"],
        nicaragua: ["*"],
        panama: ["*"],
        tanzania: ["*"],
        srilanka: ["*"],
        ethiopia: ["*"],
        chile: ["*"],
        philip: ["*"],
        turkey: ["*"],
        russia: ["*"],
        kenya: ["*"],
        lesotho: ["*"],
        mexico: ["*"],
        nigeria: ["*"],
        usa: ["*"],
        brazil: ["*"],
        columbia: ["*"],
        ivorycost: ["*"],
        ecuador: ["*"],
        namibia: ["*"],
        peru: ["*"],
        southsudan: ["*"],
        uruguay: ["*"],
        uzbekistan: ["*"],
        venezuela: ["*"],
        ukraine: ["*"],
        costarica: ["*"],
        kazakhastan: ["*"],
        pakistan: ["*"],
        costademarfil: ["*"],
        paraguay: ["*"],
        rwanda: ["*"],
        uganda: ["*"],
    },
};

